hive_api:
  base_url: "https://hive.home.deepblack.cloud"
  api_key: ""
  timeout: "30s"

agent:
  id: "test-agent"
  capabilities: ["task-coordination", "meta-discussion", "general"]
  models: ["phi3"]
  specialization: "general_developer"
  poll_interval: "60s"
  max_tasks: 1

github:
  token_file: ""

p2p:
  escalation_webhook: "https://n8n.home.deepblack.cloud/webhook-test/human-escalation"

logging:
  level: "debug"